name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install requirements
        run: |
          sudo apt install -y build-essential cmake libgmp-dev libsodium-dev nasm curl m4 git wget unzip nlohmann-json3-dev

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Anvil
        run: |
          anvil --mnemonic "myth like bonus scare over problem client lizard pioneer submit female collect" &

      - name: Deploy on Anvil
        run: |
          . ~/.bashrc && sleep 5 && git clone https://github.com/worm-privacy/worm && cd worm && forge create --rpc-url http://127.0.0.1:8545 src/BETH.sol:BETH --private-key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d --broadcast && forge create --rpc-url http://127.0.0.1:8545 src/WORM.sol:WORM --private-key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d --broadcast --constructor-args 0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab

      - name: Download params
        run: |
          make download_params WGET_ARGS=-q

      - name: Burn!
        run: |
          . ~/.bashrc && worm-miner burn --network anvil --private-key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d --amount 1.0 --spend 1.0